[phases.setup]
nixPkgs = ["python311"]

[phases.install]
# यहाँ हम Force कर रहे हैं कि ब्राउज़र उसी फोल्डर में जाए जो हमने Variable में सेट किया है
cmds = [
    "pip install -r requirements.txt",
    "PLAYWRIGHT_BROWSERS_PATH=/app/.cache/ms-playwright playwright install chromium --with-deps"
]

[phases.start]
cmds = ["python main.py"]
